/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import Controller.LocacaoController;
import Model.Locacao;

/**
 *
 * @author PC
 */
public class JanelaPesqAluguel extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPesqAluguel
     */
    public JanelaPesqAluguel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edtDevolucao = new javax.swing.JTextField();
        edtMulta = new javax.swing.JTextField();
        edtSaida = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        edtPesquisa1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setTitle("Pesquisar Aluguel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Devolver VeÃ­culo"));

        jLabel1.setText("Data DevoluÃ§Ã£o");

        jLabel2.setText("Multa");

        jLabel3.setText("Km SaÃ­da");
        
        //SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
        btnDevolver.setText("Devolver");//SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
        btnDevolver.addActionListener(new ActionListener() {//SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
        	//SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
			@Override
			public void actionPerformed(ActionEvent e) {
				clicouDevolver();//SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
				//SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
			}
		});//SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
        //SE RETIRAR A FUNÇÃO CLICOU DEVOLVER PARA DE FUNCIONAR O BOTÃO
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(edtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(edtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CÃ³digo Aluguel", "Nome Cliente", "Data Aluguel", "Data Prazo", "Data DevoluÃ§Ã£o"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Selecione o tipo de pesquisa"));
        
        //SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
        jButton2.setText("Pesquisar");//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
        jButton2.addActionListener(new ActionListener() {//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
        	//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
			@Override//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
			public void actionPerformed(ActionEvent e) {//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
				clicouPesquisar();//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
				//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
			}//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR
		});//SE RETIRAR A FUNÇÃO CLICOU PESQUISAR O BOTÃO PARA DE FUNCIONAR

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edtPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //FUNCOES PARA ATIVAR BOTOES -----------------------------------------------------------------
    String dataLocacao;
    int idLocacao;
    Locacao locacao= null;
    public void clicouPesquisar() {
    	LocacaoController lc= new LocacaoController();
    	
    	idLocacao= Integer.parseInt(edtPesquisa1.getText());
    	
    	try {
    		//O OBJETO LOCACAO RECEBE A LOCACAO PESQUISADA
			locacao= lc.consultarLocacao(idLocacao);
			//RETORNAR OS DADOS NA GRID
		} catch (SQLException e) {
			JOptionPane.showConfirmDialog(null, "Nï¿½o foi possï¿½vel pesquisar o veiculo"
					+ " erro no Banco de Dados" + e.getLocalizedMessage());
		}
    }
    public void clicouDevolver() {
    	LocacaoController lc= new LocacaoController();
    	
    	String dataDevolucao, horaDevolucao, horaLocacao;
    	long quilometragem;
    	int devolvido;
    	double valor;
    	dataDevolucao= edtDevolucao.getText();
    	horaDevolucao= "";
    	horaLocacao= locacao.getDataLocacao();
    	quilometragem= Long.parseLong(edtSaida.getText());
    	devolvido= 1;
    	valor= (Double.parseDouble(edtMulta.getText()))+locacao.getValorCaucao();
    	
    	try {
			lc.atualizarLocacao(idLocacao, locacao.getDataLocacao(), dataDevolucao,
					horaLocacao, horaDevolucao, valor, devolvido);
			//retornar a locaï¿½ï¿½o na grid
		} catch (SQLException e) {
			JOptionPane.showConfirmDialog(null, "Nao foi possivel pesquisar o veiculo"
					+ " erro no Banco de Dados" + e.getLocalizedMessage());
		}
    	
    }
  //FUNCOES PARA ATIVAR BOTOES -----------------------------------------------------------------

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPesqAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JTextField edtDevolucao;
    private javax.swing.JTextField edtMulta;
    private javax.swing.JTextField edtPesquisa1;
    private javax.swing.JTextField edtSaida;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
