/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import Controller.ClienteController;
import Model.Cliente;

/**
 *
 * @author PC
 */
public class JanelaPesqCliente extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPesqCliente
     */
    public JanelaPesqCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Pesquisar Cliente");

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        
        //SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
        btnExcluir.setText("Excluir");//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
        btnExcluir.addActionListener(new ActionListener() {//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
        	//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
			@Override//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
			public void actionPerformed(ActionEvent e) {//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
				clicouExcluir();//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
				//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
			}//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
		});//SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
      //SE RETIRAR O ADDACTIONLISTENER OU A FUNCAO CLICOU EXCLUIR O BOTAO PARA DE FUNCIONAR
        jLabel1.setText("Nome:");
        
        //SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
        btnPesquisar.setText("Pesquisar");//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
        btnPesquisar.addActionListener(new ActionListener() {//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
        	//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
			@Override
			public void actionPerformed(ActionEvent e) {//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
				clicouPesquisar();//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
				//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
			}//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR
		});//SE RETIRAR ADDACIONT E FUNCAO CLICOUPESQUISAR O BOTAO PARA DE FUNCIONAR

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "CPF", "Endereço", "EmailL", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //FUNCIONALIDADES E BOTOES --------------------------------------------------------------------------
    public void clicouPesquisar() {
    	ClienteController cc= new ClienteController();
    	String nomeCliente;
    	nomeCliente= edtPesquisa.getText();
    	try {
			Cliente c= cc.consultarCliente(nomeCliente);
		} catch (SQLException e) {
			JOptionPane.showConfirmDialog(null, "Nao foi possivel perquisar o cliente"
					+ " erro no Banco de Dados" + e.getLocalizedMessage());
		}    	
    }
    public void clicouExcluir() {
    	JOptionPane.showConfirmDialog(this, "Nao e possivel excluir!!!");
    }
    //FUNCIONALIDADES E BOTOES --------------------------------------------------------------------------

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        new JanelaEditarCliente().setVisible(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPesqCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPesqCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
