/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import Controller.VeiculoController;
import Model.TipoVeiculoAbstractFactory;
import Model.Veiculo;

/**
 *
 * @author PC
 */
public class JanelaVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaVeiculos
     */
    public JanelaVeiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtTipo = new javax.swing.JTextField();
        edtPlaca = new javax.swing.JTextField();
        edtKM = new javax.swing.JTextField();
        edtDiaria = new javax.swing.JTextField();
        edtModelo = new javax.swing.JTextField();
        edtChassi = new javax.swing.JTextField();
        edtRenavam = new javax.swing.JTextField();
        edtCor = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setTitle("Cadastrar Veiculo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tipo de VEICULO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Chassi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("KM Atual");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Valor da DIARIA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Placa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Modelo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Cor");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("RENAVAM");

        edtTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTipoActionPerformed(evt);
            }
        });

        edtPlaca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPlacaActionPerformed(evt);
            }
        });

        edtKM.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtKMActionPerformed(evt);
            }
        });

        edtDiaria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDiariaActionPerformed(evt);
            }
        });

        edtModelo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtModeloActionPerformed(evt);
            }
        });

        edtChassi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        edtRenavam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        edtCor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        
      //SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new ActionListener() { //SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR
        	//SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR
			@Override
			public void actionPerformed(ActionEvent arg0) {//SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR
				clicouSalvar();
				//SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR
			}
		});//SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR
      //SE ALTERAR O ADD ACTION PARA DE FUNCIONAR O BOTÃO SALVAR

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(edtTipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edtModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtChassi, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(edtCor))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(edtRenavam, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(edtKM))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(edtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addComponent(edtDiaria))))))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(edtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtRenavam))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(edtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(edtKM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2))))))))
                .addGap(34, 34, 34)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //FUNÇÃO PARA AÇÃO DO BOTÃO ------------------------------------------------------------------
	private void clicouSalvar() {
		VeiculoController vc= new VeiculoController();
		
		String modelo, tipoVeiculo, placa, cor, chassi, status;
		int tipoCombustivel= 1;
		int nPortas= 1;
		int idModeloVeiculo = 0;
		long quilometragem;
		long renavam;
		double valorLocacao;
		modelo= edtModelo.getText();
		tipoVeiculo= edtTipo.getText();
		placa= edtPlaca.getText();
		cor= edtCor.getText();
		chassi= edtChassi.getText();
		status= "patio";
		quilometragem= Long.parseLong(edtKM.getText());
		renavam= Long.parseLong(edtRenavam.getText());
		valorLocacao= Double.parseDouble(edtDiaria.getText());
				
		//escolher o tipo do objeto veiculo
		TipoVeiculoAbstractFactory objTipoVeiculoAbstractFactory= TipoVeiculoAbstractFactory.getInstance(tipoVeiculo);
		//escolher o modelo do objeto veiculo
		Veiculo veiculo= objTipoVeiculoAbstractFactory.getVeiculo(modelo);
		
		switch (modelo) {
		case "celta":
			idModeloVeiculo= 1;
			break;
		case "gol":
			idModeloVeiculo= 2;
			break;
		case "palio":
			idModeloVeiculo= 3;
			break;
		case "s10":
			idModeloVeiculo= 4;
			break;
		case "toro":
			idModeloVeiculo= 5;
			break;
		case "uno":
			idModeloVeiculo= 6;
			break;

		default:
			break;
		}
		
		try {
			vc.cadastrarVeiculo(veiculo, placa, cor, nPortas, quilometragem, tipoCombustivel, renavam, chassi, valorLocacao, status, idModeloVeiculo);
		} catch (SQLException e) {
			JOptionPane.showConfirmDialog(null, "Nï¿½o foi possï¿½vel alugar"
					+ " erro no Banco de Dados" + e.getLocalizedMessage());
		}
		
	}
	//fim FUNÇÃO PARA AÇÃO DO BOTÃO ------------------------------------------------------------------

    private void edtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPlacaActionPerformed

    private void edtKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtKMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtKMActionPerformed

    private void edtDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDiariaActionPerformed

    private void edtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtModeloActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtChassi;
    private javax.swing.JTextField edtCor;
    private javax.swing.JTextField edtDiaria;
    private javax.swing.JTextField edtKM;
    private javax.swing.JTextField edtModelo;
    private javax.swing.JTextField edtPlaca;
    private javax.swing.JTextField edtRenavam;
    private javax.swing.JTextField edtTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
